version: "3"
services:
  beershop:
    image: beershop
    ports:
      - "8080:8080"
    networks:
      - newNet
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    networks:
      - newNet
    environment:
      - MYSQL_ROOT_PASSWORD=root1234!
      - MYSQL_DATABASE=beershop

networks:
  newNet: